"""
=========================================================
Recommendation CRUD Operations
=========================================================
"""

from sqlalchemy.orm import Session

from database.models import Recommendation

from database.schemas.recommendation_schema import (
    RecommendationCreate,
    RecommendationUpdate,
)

# =====================================================
# Standard CRUD Operations
# =====================================================

def create_recommendation(
    db: Session,
    recommendation: RecommendationCreate,
):
    """
    Create a recommendation manually through the CRUD API.
    """

    db_recommendation = Recommendation(
        **recommendation.model_dump()
    )

    db.add(db_recommendation)
    db.commit()
    db.refresh(db_recommendation)

    return db_recommendation


def get_recommendation(
    db: Session,
    recommendation_id: int,
):
    """
    Get recommendation by ID.
    """

    return (
        db.query(Recommendation)
        .filter(
            Recommendation.id == recommendation_id
        )
        .first()
    )


def get_recommendations(
    db: Session,
):
    """
    Get all recommendations.
    """

    return db.query(Recommendation).all()


def update_recommendation(
    db: Session,
    recommendation_id: int,
    recommendation_update: RecommendationUpdate,
):
    """
    Update recommendation.
    """

    recommendation = get_recommendation(
        db,
        recommendation_id,
    )

    if recommendation is None:
        return None

    update_data = recommendation_update.model_dump(
        exclude_unset=True
    )

    for key, value in update_data.items():
        setattr(
            recommendation,
            key,
            value,
        )

    db.commit()
    db.refresh(recommendation)

    return recommendation


def delete_recommendation(
    db: Session,
    recommendation_id: int,
):
    """
    Delete recommendation.
    """

    recommendation = get_recommendation(
        db,
        recommendation_id,
    )

    if recommendation is None:
        return None

    db.delete(recommendation)
    db.commit()

    return recommendation


# =====================================================
# Machine Learning Operations
# =====================================================

def create_ml_recommendation(
    db: Session,
    prediction_id: int,
    recommended_setpoint: float,
    expected_savings: float,
    reason: str,
    llm_response: str | None = None,
):
    """
    Save recommendation generated by the ML optimizer.
    """

    recommendation = Recommendation(
        prediction_id=prediction_id,
        recommended_setpoint=recommended_setpoint,
        expected_savings=expected_savings,
        reason=reason,
        llm_response=llm_response,
    )

    db.add(recommendation)
    db.commit()
    db.refresh(recommendation)

    return recommendation


def get_latest_recommendation(
    db: Session,
):
    """
    Get the most recent recommendation.
    """

    return (
        db.query(Recommendation)
        .order_by(
            Recommendation.created_at.desc()
        )
        .first()
    )


def get_recommendations_by_prediction(
    db: Session,
    prediction_id: int,
):
    """
    Get all recommendations for a prediction.
    """

    return (
        db.query(Recommendation)
        .filter(
            Recommendation.prediction_id == prediction_id
        )
        .order_by(
            Recommendation.created_at.desc()
        )
        .all()
    )


def get_recommendation_history(
    db: Session,
):
    """
    Get complete recommendation history.
    """

    return (
        db.query(Recommendation)
        .order_by(
            Recommendation.created_at.desc()
        )
        .all()
    )